global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dnabert2'
    static_configs:
      - targets: ['dnabert2-server:8011']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'lucaone'
    static_configs:
      - targets: ['lucaone-server:8012']
    metrics_path: /metrics
    scrape_interval: 15s