name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install project with docs extras
        run: |
          uv pip install -e .[docs] --system

      - name: Build docs (warnings as errors)
        run: |
          sphinx-build -W -b html docs docs/_build/html | cat

      - name: Upload built docs artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

